version: '3.7'

services:

  nginx:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 80:80

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cypress/snapshots:/usr/src/app/cypress/snapshots
      - ./cypress/screenshots:/usr/src/app/cypress/screenshots
    depends_on:
      - nginx
    network_mode: host
